class Article {
  final String text;
  final String domain;
  final String by;
  final String age;
  final int score;
  final int commentsCount;

  const Article(
      {this.text,
      this.domain,
      this.by,
      this.age,
      this.score,
      this.commentsCount});
}

final articles = [
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5",
    domain: "pub.dartlang.org",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-52",
    domain: "pub.dartlang.org",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-53",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-54",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-55",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-56",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-537",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-548",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-559",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-560",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5110",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5211",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5312",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5413",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5514",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5615",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5316",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5417",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5518",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5619",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5120",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5221",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5322",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5423",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5524",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5625",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5326",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5427",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5528",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Circular shock Acoustic Waves in Ionosphere Triggered by Launch of Formosat-5629",
    domain: "willey.com",
    by: "zdw",
    age: "3 hours",
    score: 177,
    commentsCount: 62,
  ),
];
